# This is a basic workflow to help you get started with Actions

name: Release on Webhook

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag-Name or Version
        required: true
      pre-release:
        description: Pre-release ?
        required: true
        default: 'false'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - run: npm install
      - run: npm run build:prepare
      - run: npm run build:all

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag-name }}
          release_name: Release V${{ github.event.inputs.tag-name }}
          draft: false
          prerelease: ${{ github.event.inputs.pre-release }}
      - name: Upload Release Asset Windows
        id: upload-release-asset-exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./release/out/memebox.exe
          asset_name: memebox.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Release Asset Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./release/out/memebox-linux
          asset_name: memebox-linux
          asset_content_type: application/octet-stream

      - name: Zip Mac App
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./release/out/memebox-macos.zip release/out/memebox-macos.app

      - name: Upload Release Asset Mac
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./release/out/memebox-macos.zip
          asset_name: memebox-macos.zip
          asset_content_type: application/octet-stream
